select * from member;
SELECT * FROM MEMBER_BIZ;
select * from HOME_QNA;
-- type컬럼 삭제하기
alter table product_order drop column type; 
alter table custom_order drop column type;


-- MEMBER_BIZ의 MEMBER_CODE를 자동으로 업데이트 해주는 트리거
create or replace TRIGGER TRG_MEMCODE
AFTER
INSERT ON MEMBER_BIZ
FOR EACH ROW
DECLARE
BEGIN
	DBMS_OUTPUT.PUT_LINE('아이디 : ' || :OLD.M_ID);
	DBMS_OUTPUT.PUT_LINE('변경 전 코드 값 : ' || :OLD.M_NUM);
	UPDATE MEMBER
	SET M_NUM ='3'
	WHERE M_ID = :OLD.M_ID;
    DBMS_OUTPUT.PUT_LINE('아이디 : ' || :OLD.M_ID);
	DBMS_OUTPUT.PUT_LINE('변경 전 코드 값 : ' || :NEW.M_NUM);
END ;
/


/* SEQ_C_B_NUM */
CREATE SEQUENCE LIKEYCAKEY.SEQ_C_B_NUM 
   MINVALUE 1
   MAXVALUE 9999999999999999999999999999
   INCREMENT BY 1
   NOCACHE
   START WITH 1;

/* SEQ_H_Q_C_NUM */
CREATE SEQUENCE LIKEYCAKEY.SEQ_H_Q_C_NUM 
   MINVALUE 1
   MAXVALUE 9999999999999999999999999999
   INCREMENT BY 1
   NOCACHE
   START WITH 1;

/* SEQ_H_Q_NUM */
CREATE SEQUENCE LIKEYCAKEY.SEQ_H_Q_NUM 
   MINVALUE 1
   MAXVALUE 9999999999999999999999999999
   INCREMENT BY 1
   NOCACHE
   START WITH 1;

/* SEQ_P_B_NUM */
CREATE SEQUENCE LIKEYCAKEY.SEQ_P_B_NUM 
   MINVALUE 1
   MAXVALUE 9999999999999999999999999999
   INCREMENT BY 1
   NOCACHE
   START WITH 1;

/* SEQ_P_Q_C_NUM */
CREATE SEQUENCE LIKEYCAKEY.SEQ_P_Q_C_NUM 
   MINVALUE 1
   MAXVALUE 9999999999999999999999999999
   INCREMENT BY 1
   NOCACHE
   START WITH 1;

/* SEQ_P_Q_NUM */
CREATE SEQUENCE LIKEYCAKEY.SEQ_P_Q_NUM 
   MINVALUE 1
   MAXVALUE 9999999999999999999999999999
   INCREMENT BY 1
   NOCACHE
   START WITH 1;

/* SEQ_P_R_C_NUM */
CREATE SEQUENCE LIKEYCAKEY.SEQ_P_R_C_NUM 
   MINVALUE 1
   MAXVALUE 9999999999999999999999999999
   INCREMENT BY 1
   NOCACHE
   START WITH 1;

/* SEQ_P_R_NUM */
CREATE SEQUENCE LIKEYCAKEY.SEQ_P_R_NUM 
   MINVALUE 1
   MAXVALUE 9999999999999999999999999999
   INCREMENT BY 1
   NOCACHE
   START WITH 1;

/* BLACK_LIST */
CREATE TABLE LIKEYCAKEY.BLACK_LIST (
	BLACK_NO VARCHAR2(20) NOT NULL, /* 번호 */
	RUSER VARCHAR2(50) NOT NULL, /* 신고유저 */
	TUSER VARCHAR2(50) NOT NULL, /* 신고당한유저 */
	P_B_NUM NUMBER, /* 완제품 신고당한  게시글 번호 */
	C_B_NUM NUMBER /* 커스텀 신고당한 게시글 번호 */
);

COMMENT ON TABLE LIKEYCAKEY.BLACK_LIST IS 'BLACK_LIST';

COMMENT ON COLUMN LIKEYCAKEY.BLACK_LIST.BLACK_NO IS '번호';

COMMENT ON COLUMN LIKEYCAKEY.BLACK_LIST.RUSER IS '신고유저';

COMMENT ON COLUMN LIKEYCAKEY.BLACK_LIST.TUSER IS '신고당한유저';

COMMENT ON COLUMN LIKEYCAKEY.BLACK_LIST.P_B_NUM IS '완제품 신고당한  게시글 번호';

COMMENT ON COLUMN LIKEYCAKEY.BLACK_LIST.C_B_NUM IS '커스텀 신고당한 게시글 번호';

CREATE UNIQUE INDEX LIKEYCAKEY.BLACK_LIST_PK
	ON LIKEYCAKEY.BLACK_LIST (
		BLACK_NO ASC
	);

ALTER TABLE LIKEYCAKEY.BLACK_LIST
	ADD
		CONSTRAINT BLACK_LIST_PK
		PRIMARY KEY (
			BLACK_NO
		);

/* 커스터마이징 케이크 상세페이지 */
CREATE TABLE LIKEYCAKEY.CUSTOM_BOARD (
	C_B_NUM NUMBER NOT NULL, /* 게시글 번호 */
	M_ID VARCHAR2(50) NOT NULL, /* 회원 아이디 */
	C_B_MINI_TITLE VARCHAR2(100) NOT NULL, /* 게시글 소제목 */
	C_B_MINI_CONTENT VARCHAR2(2000) NOT NULL, /* 게시글 소내용 */
	C_B_CONTENT VARCHAR2(4000) NOT NULL, /* 게시글 내용 */
	C_B_LIKE NUMBER NOT NULL, /* 게시글 좋아요 수 */
	C_B_READCNT NUMBER NOT NULL, /* 게시글 조회 수 */
	C_B_TAG VARCHAR2(2000) NOT NULL, /* 게시글 태그 */
	C_B_WARN VARCHAR2(2000) NOT NULL, /* 예약시 주의사항 */
	C_B_NAME VARCHAR2(100) NOT NULL, /* 게시글 이름 */
	C_B_PRICE NUMBER NOT NULL, /* 기본 가격 */
	C_B_STATUS NUMBER NOT NULL /* 게시글 상태(블럭) */
);

COMMENT ON TABLE LIKEYCAKEY.CUSTOM_BOARD IS '커스터마이징 케이크 상세페이지';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_BOARD.C_B_NUM IS '게시글 번호';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_BOARD.M_ID IS '회원 아이디';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_BOARD.C_B_MINI_TITLE IS '게시글 소제목';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_BOARD.C_B_MINI_CONTENT IS '게시글 소내용';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_BOARD.C_B_CONTENT IS '게시글 내용';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_BOARD.C_B_LIKE IS '게시글 좋아요 수';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_BOARD.C_B_READCNT IS '게시글 조회 수';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_BOARD.C_B_TAG IS '게시글 태그';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_BOARD.C_B_WARN IS '예약시 주의사항';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_BOARD.C_B_NAME IS '게시글 이름';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_BOARD.C_B_PRICE IS '기본 가격';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_BOARD.C_B_STATUS IS '게시글 상태(블럭)';

CREATE UNIQUE INDEX LIKEYCAKEY.PK_CUSTOM_BOARD
	ON LIKEYCAKEY.CUSTOM_BOARD (
		C_B_NUM ASC
	);

ALTER TABLE LIKEYCAKEY.CUSTOM_BOARD
	ADD
		CONSTRAINT PK_CUSTOM_BOARD
		PRIMARY KEY (
			C_B_NUM
		);

/* 커스텀 크림 */
CREATE TABLE LIKEYCAKEY.CUSTOM_CREAM (
	CR_NUM VARCHAR2(20) NOT NULL, /* 크림 번호 */
	M_ID VARCHAR2(50) NOT NULL, /* 사업자 회원 아이디 */
	CR_NAME VARCHAR2(50) NOT NULL, /* 크림 종류 */
	CR_PRICE NUMBER NOT NULL /* 크림 추가 가격 */
);

COMMENT ON TABLE LIKEYCAKEY.CUSTOM_CREAM IS '커스텀 크림';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_CREAM.CR_NUM IS '크림 번호';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_CREAM.M_ID IS '사업자 회원 아이디';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_CREAM.CR_NAME IS '크림 종류';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_CREAM.CR_PRICE IS '크림 추가 가격';

CREATE UNIQUE INDEX LIKEYCAKEY.PK_COUSTOM_CREAM
	ON LIKEYCAKEY.CUSTOM_CREAM (
		CR_NUM ASC
	);

ALTER TABLE LIKEYCAKEY.CUSTOM_CREAM
	ADD
		CONSTRAINT PK_COUSTOM_CREAM
		PRIMARY KEY (
			CR_NUM
		);

/* 커스텀 케이크 주문 */
CREATE TABLE LIKEYCAKEY.CUSTOM_ORDER (
	C_O_NUM NUMBER NOT NULL, /* 커스텀 케이크 주문 번호 */
	C_B_NUM NUMBER NOT NULL, /* 커스텀 케이크 페이지 참조 번호 */
	S_NUM NUMBER NOT NULL, /* 주문 진행상태 */
	M_ID VARCHAR2(50) NOT NULL, /* 주문자 */
	BIZ_DELIVERY NUMBER, /* 배송비 */
	C_O_MEMO VARCHAR2(300), /* 배송 메모 */
	C_O_DATE DATE NOT NULL, /* 커스텀 케이크 주문 일자 */
	C_O_BOOKDATE DATE NOT NULL, /* 커스텀 케이크 예약 날짜 */
	C_O_CNT NUMBER NOT NULL, /* 커스텀 케이크 주문수량 */
	C_O_PRICE NUMBER NOT NULL, /* 총 삼품 가격 */
	C_O_TEXT VARCHAR2(60), /* 케이크 문구 */
	C_O_SIZE VARCHAR2(20) NOT NULL, /* 커스텀 케이크 사이즈 */
	C_O_SHEET VARCHAR2(20) NOT NULL, /* 커스텀 케이크 선택 시트 */
	C_O_TOPPING VARCHAR2(20) NOT NULL, /* 커스텀 케이크 선택 토핑 */
	C_O_CREAM VARCHAR2(20) NOT NULL, /* 커스텀 케이크 선택 크림 */
	C_O_REC_NAME VARCHAR2(50) NOT NULL, /* 받는 사람 이름 */
	C_O_REC_CP VARCHAR2(50) NOT NULL, /* 받는 사람 전화번호 */
	C_O_REC_POST VARCHAR2(10) NOT NULL, /* 받는 사람 우편번호 */
	C_O_REC_BASIC_ADDR VARCHAR2(1000) NOT NULL, /* 받는 사람 기본주소 */
	C_O_REC_DETAIL_ADDR VARCHAR2(1000) NOT NULL /* 받는 사람 상세주소 */
);

COMMENT ON TABLE LIKEYCAKEY.CUSTOM_ORDER IS '커스텀 케이크 주문';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_ORDER.C_O_NUM IS '커스텀 케이크 주문 번호';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_ORDER.C_B_NUM IS '커스텀 케이크 페이지 참조 번호';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_ORDER.S_NUM IS '주문 진행상태';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_ORDER.M_ID IS '주문자';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_ORDER.BIZ_DELIVERY IS '배송비';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_ORDER.C_O_MEMO IS '배송 메모';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_ORDER.C_O_DATE IS '커스텀 케이크 주문 일자';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_ORDER.C_O_BOOKDATE IS '커스텀 케이크 예약 날짜';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_ORDER.C_O_CNT IS '커스텀 케이크 주문수량';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_ORDER.C_O_PRICE IS '총 삼품 가격';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_ORDER.C_O_TEXT IS '케이크 문구';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_ORDER.C_O_SIZE IS '커스텀 케이크 사이즈';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_ORDER.C_O_SHEET IS '커스텀 케이크 선택 시트';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_ORDER.C_O_TOPPING IS '커스텀 케이크 선택 토핑';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_ORDER.C_O_CREAM IS '커스텀 케이크 선택 크림';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_ORDER.C_O_REC_NAME IS '받는 사람 이름';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_ORDER.C_O_REC_CP IS '받는 사람 전화번호';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_ORDER.C_O_REC_POST IS '받는 사람 우편번호';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_ORDER.C_O_REC_BASIC_ADDR IS '받는 사람 기본주소';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_ORDER.C_O_REC_DETAIL_ADDR IS '받는 사람 상세주소';

CREATE UNIQUE INDEX LIKEYCAKEY.PK_CUSTOM_ORDER
	ON LIKEYCAKEY.CUSTOM_ORDER (
		C_O_NUM ASC
	);

ALTER TABLE LIKEYCAKEY.CUSTOM_ORDER
	ADD
		CONSTRAINT PK_CUSTOM_ORDER
		PRIMARY KEY (
			C_O_NUM
		);

/* 커스텀 시트 */
CREATE TABLE LIKEYCAKEY.CUSTOM_SHEET (
	SH_NUM VARCHAR2(20) NOT NULL, /* 시트 번호 */
	M_ID VARCHAR2(50) NOT NULL, /* 사업자 회원 아이디 */
	SH_NAME VARCHAR2(50) NOT NULL, /* 시트 종류 */
	SH_PRICE NUMBER NOT NULL /* 시트 추가 가격 */
);

COMMENT ON TABLE LIKEYCAKEY.CUSTOM_SHEET IS '커스텀 시트';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_SHEET.SH_NUM IS '시트 번호';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_SHEET.M_ID IS '사업자 회원 아이디';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_SHEET.SH_NAME IS '시트 종류';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_SHEET.SH_PRICE IS '시트 추가 가격';

CREATE UNIQUE INDEX LIKEYCAKEY.PK_CUSTOM_SHEET
	ON LIKEYCAKEY.CUSTOM_SHEET (
		SH_NUM ASC
	);

ALTER TABLE LIKEYCAKEY.CUSTOM_SHEET
	ADD
		CONSTRAINT PK_CUSTOM_SHEET
		PRIMARY KEY (
			SH_NUM
		);

/* 커스텀 사이즈 */
CREATE TABLE LIKEYCAKEY.CUSTOM_SIZE (
	SIZE_NUM VARCHAR2(20) NOT NULL, /* 사이즈 번호 */
	M_ID VARCHAR2(50) NOT NULL, /* 사업자 회원 아이디 */
	SIZE_NAME VARCHAR2(50) NOT NULL, /* 사이즈 종류 */
	SIZE_PRICE NUMBER NOT NULL /* 사이즈 추가 가격 */
);

COMMENT ON TABLE LIKEYCAKEY.CUSTOM_SIZE IS '커스텀 사이즈';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_SIZE.SIZE_NUM IS '사이즈 번호';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_SIZE.M_ID IS '사업자 회원 아이디';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_SIZE.SIZE_NAME IS '사이즈 종류';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_SIZE.SIZE_PRICE IS '사이즈 추가 가격';

CREATE UNIQUE INDEX LIKEYCAKEY.PK_CUSTOM_SIZE
	ON LIKEYCAKEY.CUSTOM_SIZE (
		SIZE_NUM ASC
	);

ALTER TABLE LIKEYCAKEY.CUSTOM_SIZE
	ADD
		CONSTRAINT PK_CUSTOM_SIZE
		PRIMARY KEY (
			SIZE_NUM
		);

/* 커스텀 토핑 */
CREATE TABLE LIKEYCAKEY.CUSTOM_TOPPING (
	TP_NUM VARCHAR2(20) NOT NULL, /* 토핑 번호 */
	M_ID VARCHAR2(50) NOT NULL, /* 사업자 회원 아이디 */
	TP_NAME VARCHAR2(50) NOT NULL, /* 토핑 종류 */
	TP_PRICE NUMBER NOT NULL /* 토핑 추가 가격 */
);

COMMENT ON TABLE LIKEYCAKEY.CUSTOM_TOPPING IS '커스텀 토핑';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_TOPPING.TP_NUM IS '토핑 번호';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_TOPPING.M_ID IS '사업자 회원 아이디';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_TOPPING.TP_NAME IS '토핑 종류';

COMMENT ON COLUMN LIKEYCAKEY.CUSTOM_TOPPING.TP_PRICE IS '토핑 추가 가격';

CREATE UNIQUE INDEX LIKEYCAKEY.PK_CUSTOM_TOPPING
	ON LIKEYCAKEY.CUSTOM_TOPPING (
		TP_NUM ASC
	);

ALTER TABLE LIKEYCAKEY.CUSTOM_TOPPING
	ADD
		CONSTRAINT PK_CUSTOM_TOPPING
		PRIMARY KEY (
			TP_NUM
		);

/* 배송관련 테이블 */
CREATE TABLE LIKEYCAKEY.DELIVERY (
	D_NUM VARCHAR2(20) NOT NULL, /* 운송장 번호 */
	D_DATE DATE NOT NULL, /* 처리 일시 */
	D_LOCATION VARCHAR2(100) NOT NULL, /* 택배 현재 위치 */
	DV_STATUS VARCHAR2(50) NOT NULL, /* 배송 상태 */
	DM_CP VARCHAR2(20) /* 배송기사 전화번호 */
);

COMMENT ON TABLE LIKEYCAKEY.DELIVERY IS '배송관련 테이블';

COMMENT ON COLUMN LIKEYCAKEY.DELIVERY.D_NUM IS '운송장 번호';

COMMENT ON COLUMN LIKEYCAKEY.DELIVERY.D_DATE IS '처리 일시';

COMMENT ON COLUMN LIKEYCAKEY.DELIVERY.D_LOCATION IS '택배 현재 위치';

COMMENT ON COLUMN LIKEYCAKEY.DELIVERY.DV_STATUS IS '배송 상태';

COMMENT ON COLUMN LIKEYCAKEY.DELIVERY.DM_CP IS '배송기사 전화번호';

/* 배송 기본 정보 */
CREATE TABLE LIKEYCAKEY.DELIVERY_BASIC (
	D_NUM VARCHAR2(20) NOT NULL, /* 운송장 번호 */
	P_O_NUM NUMBER NOT NULL, /* 주문번호 */
	D_COMPANY VARCHAR2(300) NOT NULL /* 택배사 */
);

COMMENT ON TABLE LIKEYCAKEY.DELIVERY_BASIC IS '배송 기본 정보';

COMMENT ON COLUMN LIKEYCAKEY.DELIVERY_BASIC.D_NUM IS '운송장 번호';

COMMENT ON COLUMN LIKEYCAKEY.DELIVERY_BASIC.P_O_NUM IS '주문번호';

COMMENT ON COLUMN LIKEYCAKEY.DELIVERY_BASIC.D_COMPANY IS '택배사';

CREATE UNIQUE INDEX LIKEYCAKEY.PK_DELIVERY_BASIC
	ON LIKEYCAKEY.DELIVERY_BASIC (
		D_NUM ASC
	);

ALTER TABLE LIKEYCAKEY.DELIVERY_BASIC
	ADD
		CONSTRAINT PK_DELIVERY_BASIC
		PRIMARY KEY (
			D_NUM
		);

/* 홈페이지 관련 QNA */
CREATE TABLE LIKEYCAKEY.HOME_QNA (
	H_Q_NUM NUMBER NOT NULL, /* QNA 게시글 번호 */
	M_ID VARCHAR2(50) NOT NULL, /* QNA 게시글 글쓴이 */
	H_Q_CONTENT VARCHAR2(4000) NOT NULL, /* QNA 게시글 내용 */
	H_Q_TITLE VARCHAR2(500) NOT NULL, /* QNA 게시글 제목 */
	H_Q_DATE DATE NOT NULL, /* QNA 게시글 작성일 */
	H_Q_RE_REF NUMBER NOT NULL, /* 원글 참조 번호 */
	H_Q_RE_LEV NUMBER NOT NULL, /* 답글 레벨 */
	H_Q_RE_SEQ NUMBER NOT NULL /* 답글 시퀀스 */
);

COMMENT ON TABLE LIKEYCAKEY.HOME_QNA IS '홈페이지 관련 QNA';

COMMENT ON COLUMN LIKEYCAKEY.HOME_QNA.H_Q_NUM IS 'QNA 게시글 번호';

COMMENT ON COLUMN LIKEYCAKEY.HOME_QNA.M_ID IS 'QNA 게시글 글쓴이';

COMMENT ON COLUMN LIKEYCAKEY.HOME_QNA.H_Q_CONTENT IS 'QNA 게시글 내용';

COMMENT ON COLUMN LIKEYCAKEY.HOME_QNA.H_Q_TITLE IS 'QNA 게시글 제목';

COMMENT ON COLUMN LIKEYCAKEY.HOME_QNA.H_Q_DATE IS 'QNA 게시글 작성일';

COMMENT ON COLUMN LIKEYCAKEY.HOME_QNA.H_Q_RE_REF IS '원글 참조 번호';

COMMENT ON COLUMN LIKEYCAKEY.HOME_QNA.H_Q_RE_LEV IS '답글 레벨';

COMMENT ON COLUMN LIKEYCAKEY.HOME_QNA.H_Q_RE_SEQ IS '답글 시퀀스';

CREATE UNIQUE INDEX LIKEYCAKEY.PK_HOME_QNA
	ON LIKEYCAKEY.HOME_QNA (
		H_Q_NUM ASC
	);

ALTER TABLE LIKEYCAKEY.HOME_QNA
	ADD
		CONSTRAINT PK_HOME_QNA
		PRIMARY KEY (
			H_Q_NUM
		);

/* 홈페이지 관련 QNA 댓글 */
CREATE TABLE LIKEYCAKEY.H_QNA_COM (
	H_Q_C_NUM NUMBER NOT NULL, /* 홈페이지 QNA 댓글 번호 */
	H_Q_NUM NUMBER NOT NULL, /* 홈페이지 QNA 게시글 참조번호 */
	M_ID VARCHAR2(50) NOT NULL, /* 홈페이지 QNA 댓글 글쓴이 */
	H_Q_C_CONTENT VARCHAR2(4000) NOT NULL, /* 홈페이지 QNA 댓글 내용 */
	H_Q_C_DATE DATE NOT NULL, /* 홈페이지 QNA 댓글 작성날짜 */
	H_Q_C_RE_LEV NUMBER NOT NULL, /* 홈페이지 QNA 댓글 레벨 */
	H_Q_C_RE_SEQ NUMBER NOT NULL /* 홈페이지 QNA 댓글 시퀀스 */
);

COMMENT ON TABLE LIKEYCAKEY.H_QNA_COM IS '홈페이지 관련 QNA 댓글';

COMMENT ON COLUMN LIKEYCAKEY.H_QNA_COM.H_Q_C_NUM IS '홈페이지 QNA 댓글 번호';

COMMENT ON COLUMN LIKEYCAKEY.H_QNA_COM.H_Q_NUM IS '홈페이지 QNA 게시글 참조번호';

COMMENT ON COLUMN LIKEYCAKEY.H_QNA_COM.M_ID IS '홈페이지 QNA 댓글 글쓴이';

COMMENT ON COLUMN LIKEYCAKEY.H_QNA_COM.H_Q_C_CONTENT IS '홈페이지 QNA 댓글 내용';

COMMENT ON COLUMN LIKEYCAKEY.H_QNA_COM.H_Q_C_DATE IS '홈페이지 QNA 댓글 작성날짜';

COMMENT ON COLUMN LIKEYCAKEY.H_QNA_COM.H_Q_C_RE_LEV IS '홈페이지 QNA 댓글 레벨';

COMMENT ON COLUMN LIKEYCAKEY.H_QNA_COM.H_Q_C_RE_SEQ IS '홈페이지 QNA 댓글 시퀀스';

CREATE UNIQUE INDEX LIKEYCAKEY.PK_H_QNA_COM
	ON LIKEYCAKEY.H_QNA_COM (
		H_Q_C_NUM ASC
	);

ALTER TABLE LIKEYCAKEY.H_QNA_COM
	ADD
		CONSTRAINT PK_H_QNA_COM
		PRIMARY KEY (
			H_Q_C_NUM
		);

/* 회원 및 관리자 */
CREATE TABLE LIKEYCAKEY.MEMBER (
	M_ID VARCHAR2(50) NOT NULL, /* 회원 아이디 */
	M_NUM NUMBER NOT NULL, /* 회원 분류 번호 */
	M_PW VARCHAR2(50) NOT NULL, /* 회원 비밀번호 */
	M_NAME VARCHAR2(50) NOT NULL, /* 회원 이름 */
	M_EMAIL VARCHAR2(100), /* 회원 이메일 */
	M_POST VARCHAR2(10), /* 회원 우편번호 */
	M_BASIC_ADDR VARCHAR2(1000), /* 회원 기본주소 */
	M_DETAIL_ADDR VARCHAR2(1000), /* 회원 상세주소 */
	M_CP VARCHAR2(50), /* 회원 전화번호 */
	M_PHOTO VARCHAR2(2000), /* 회원 사진 */
	M_BLACKCNT NUMBER, /* 신고당한 횟수 */
	M_STATUS NUMBER /* 회원의 현재 블록 상태 */
);

COMMENT ON TABLE LIKEYCAKEY.MEMBER IS '회원 및 관리자';

COMMENT ON COLUMN LIKEYCAKEY.MEMBER.M_ID IS '회원 아이디';

COMMENT ON COLUMN LIKEYCAKEY.MEMBER.M_NUM IS '회원 분류 번호';

COMMENT ON COLUMN LIKEYCAKEY.MEMBER.M_PW IS '회원 비밀번호';

COMMENT ON COLUMN LIKEYCAKEY.MEMBER.M_NAME IS '회원 이름';

COMMENT ON COLUMN LIKEYCAKEY.MEMBER.M_EMAIL IS '회원 이메일';

COMMENT ON COLUMN LIKEYCAKEY.MEMBER.M_POST IS '회원 우편번호';

COMMENT ON COLUMN LIKEYCAKEY.MEMBER.M_BASIC_ADDR IS '회원 기본주소';

COMMENT ON COLUMN LIKEYCAKEY.MEMBER.M_DETAIL_ADDR IS '회원 상세주소';

COMMENT ON COLUMN LIKEYCAKEY.MEMBER.M_CP IS '회원 전화번호';

COMMENT ON COLUMN LIKEYCAKEY.MEMBER.M_PHOTO IS '회원 사진';

COMMENT ON COLUMN LIKEYCAKEY.MEMBER.M_BLACKCNT IS '신고당한 횟수';

COMMENT ON COLUMN LIKEYCAKEY.MEMBER.M_STATUS IS '회원의 현재 블록 상태';

CREATE UNIQUE INDEX LIKEYCAKEY.PK_MEMBER
	ON LIKEYCAKEY.MEMBER (
		M_ID ASC
	);

ALTER TABLE LIKEYCAKEY.MEMBER
	ADD
		CONSTRAINT PK_MEMBER
		PRIMARY KEY (
			M_ID
		);

/* 사업지 회원 */
CREATE TABLE LIKEYCAKEY.MEMBER_BIZ (
	M_ID VARCHAR2(50) NOT NULL, /* 회원 아이디 */
	M_NUM NUMBER NOT NULL, /* 회원 분류 번호 */
	BIZ_NAME VARCHAR2(50) NOT NULL, /* 사업장 이름 */
	BIZ_PN VARCHAR2(20) NOT NULL, /* 사업장 전화번호 */
	BIZ_NUM VARCHAR2(50) NOT NULL, /* 사업자 등록번호 */
	BIZ_DELIVERY NUMBER, /* 배송비 */
	MASTER_NAME VARCHAR2(50) NOT NULL, /* 담당자 이름 */
	BIZ_DELIVERY_YN VARCHAR2(2) NOT NULL, /* 배송가능 여부 */
	BIZ_CUSTOM_YN VARCHAR2(2) NOT NULL /* 케이크 커스텀 가능여부 */
);

COMMENT ON TABLE LIKEYCAKEY.MEMBER_BIZ IS '사업지 회원';

COMMENT ON COLUMN LIKEYCAKEY.MEMBER_BIZ.M_ID IS '회원 아이디';

COMMENT ON COLUMN LIKEYCAKEY.MEMBER_BIZ.M_NUM IS '회원 분류 번호';

COMMENT ON COLUMN LIKEYCAKEY.MEMBER_BIZ.BIZ_NAME IS '사업장 이름';

COMMENT ON COLUMN LIKEYCAKEY.MEMBER_BIZ.BIZ_PN IS '사업장 전화번호';

COMMENT ON COLUMN LIKEYCAKEY.MEMBER_BIZ.BIZ_NUM IS '사업자 등록번호';

COMMENT ON COLUMN LIKEYCAKEY.MEMBER_BIZ.BIZ_DELIVERY IS '배송비';

COMMENT ON COLUMN LIKEYCAKEY.MEMBER_BIZ.MASTER_NAME IS '담당자 이름';

COMMENT ON COLUMN LIKEYCAKEY.MEMBER_BIZ.BIZ_DELIVERY_YN IS '배송가능 여부';

COMMENT ON COLUMN LIKEYCAKEY.MEMBER_BIZ.BIZ_CUSTOM_YN IS '케이크 커스텀 가능여부';

/* 회원 분류 */
CREATE TABLE LIKEYCAKEY.MEMBER_CODE (
	M_NUM NUMBER NOT NULL, /* 회원 분류 번호 */
	M_TYPE VARCHAR2(12) NOT NULL /* 회원 구분 타입 */
);

COMMENT ON TABLE LIKEYCAKEY.MEMBER_CODE IS '회원 분류';

COMMENT ON COLUMN LIKEYCAKEY.MEMBER_CODE.M_NUM IS '회원 분류 번호';

COMMENT ON COLUMN LIKEYCAKEY.MEMBER_CODE.M_TYPE IS '회원 구분 타입';

CREATE UNIQUE INDEX LIKEYCAKEY.PK_MEMBER_CODE
	ON LIKEYCAKEY.MEMBER_CODE (
		M_NUM ASC
	);

ALTER TABLE LIKEYCAKEY.MEMBER_CODE
	ADD
		CONSTRAINT PK_MEMBER_CODE
		PRIMARY KEY (
			M_NUM
		);

/* MEMBER_LIKE */
CREATE TABLE LIKEYCAKEY.MEMBER_LIKE (
	P_B_NUM NUMBER, /* 좋아요한 완제품 게시글 번호 */
	C_B_NUM NUMBER, /* 좋아요한 커스텀 게시글 번호
 */
	M_ID VARCHAR2(50) NOT NULL, /* 좋아요 누른 회원 아이디 */
	LIKE_NO NUMBER NOT NULL /* 번호 */
);

COMMENT ON TABLE LIKEYCAKEY.MEMBER_LIKE IS 'MEMBER_LIKE';

COMMENT ON COLUMN LIKEYCAKEY.MEMBER_LIKE.P_B_NUM IS '좋아요한 완제품 게시글 번호';

COMMENT ON COLUMN LIKEYCAKEY.MEMBER_LIKE.C_B_NUM IS '좋아요한 커스텀 게시글 번호
';

COMMENT ON COLUMN LIKEYCAKEY.MEMBER_LIKE.M_ID IS '좋아요 누른 회원 아이디';

COMMENT ON COLUMN LIKEYCAKEY.MEMBER_LIKE.LIKE_NO IS '번호';

CREATE UNIQUE INDEX LIKEYCAKEY.MEMBER_LIKE_PK
	ON LIKEYCAKEY.MEMBER_LIKE (
		LIKE_NO ASC
	);

ALTER TABLE LIKEYCAKEY.MEMBER_LIKE
	ADD
		CONSTRAINT MEMBER_LIKE_PK
		PRIMARY KEY (
			LIKE_NO
		);

/* 완제품 케이크 상세페이지 */
CREATE TABLE LIKEYCAKEY.PRODUCT_BOARD (
	P_B_NUM NUMBER NOT NULL, /* 게시글 번호 */
	M_ID VARCHAR2(50) NOT NULL, /* 회원 아이디 */
	P_NAME VARCHAR2(100) NOT NULL, /* 케이크 이름 */
	P_PRICE NUMBER NOT NULL, /* 케이크 가격 */
	P_IMG VARCHAR2(1000) NOT NULL, /* 케이크 이미지 */
	P_SIZE NUMBER NOT NULL, /* 케이크 규격 */
	P_CM VARCHAR2(20) NOT NULL, /* 케이크 크기(CM) */
	P_COUNT NUMBER NOT NULL, /* 케이크 재고 */
	P_COUNT_LIMIT NUMBER NOT NULL, /* 일일판매제한 개수 */
	P_B_MINI_TITLE VARCHAR2(100) NOT NULL, /* 게시글 소 제목 */
	P_B_MINI_CONTENT VARCHAR2(2000) NOT NULL, /* 게시글 소내용 */
	P_B_CONTENT VARCHAR2(4000) NOT NULL, /* 게시글 내용 */
	P_B_LIKE NUMBER NOT NULL, /* 게시글 좋아요 수 */
	P_B_READCNT NUMBER NOT NULL, /* 게시글 조회 수 */
	P_B_YN VARCHAR2(2) NOT NULL, /* 당일 구매여부 */
	P_B_WARN VARCHAR2(2000) NOT NULL, /* 예약시 주의사항 */
	P_B_TAG VARCHAR2(2000) NOT NULL, /* 게시글 태그 */
	P_B_SELLCNT NUMBER NOT NULL, /* 총 판매개수 */
	P_B_STATUS NUMBER NOT NULL /* 게시판 상태(블럭) */
);

COMMENT ON TABLE LIKEYCAKEY.PRODUCT_BOARD IS '완제품 케이크 상세페이지';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_BOARD.P_B_NUM IS '게시글 번호';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_BOARD.M_ID IS '회원 아이디';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_BOARD.P_NAME IS '케이크 이름';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_BOARD.P_PRICE IS '케이크 가격';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_BOARD.P_IMG IS '케이크 이미지';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_BOARD.P_SIZE IS '케이크 규격';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_BOARD.P_CM IS '케이크 크기(CM)';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_BOARD.P_COUNT IS '케이크 재고';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_BOARD.P_COUNT_LIMIT IS '일일판매제한 개수';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_BOARD.P_B_MINI_TITLE IS '게시글 소 제목';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_BOARD.P_B_MINI_CONTENT IS '게시글 소내용';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_BOARD.P_B_CONTENT IS '게시글 내용';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_BOARD.P_B_LIKE IS '게시글 좋아요 수';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_BOARD.P_B_READCNT IS '게시글 조회 수';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_BOARD.P_B_YN IS '당일 구매여부';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_BOARD.P_B_WARN IS '예약시 주의사항';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_BOARD.P_B_TAG IS '게시글 태그';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_BOARD.P_B_SELLCNT IS '총 판매개수';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_BOARD.P_B_STATUS IS '게시판 상태(블럭)';

CREATE UNIQUE INDEX LIKEYCAKEY.PK_PRODUCT_BOARD
	ON LIKEYCAKEY.PRODUCT_BOARD (
		P_B_NUM ASC
	);

ALTER TABLE LIKEYCAKEY.PRODUCT_BOARD
	ADD
		CONSTRAINT PK_PRODUCT_BOARD
		PRIMARY KEY (
			P_B_NUM
		);

ALTER TABLE LIKEYCAKEY.PRODUCT_BOARD
	ADD
		CONSTRAINT P_BOARD_YN_CK
		CHECK (P_B_YN IN('Y','N'));

/* 완제품 케이크 주문 */
CREATE TABLE LIKEYCAKEY.PRODUCT_ORDER (
	P_O_NUM NUMBER NOT NULL, /* 주문 번호 */
	P_B_NUM NUMBER NOT NULL, /* 참조 게시글 번호 */
	S_NUM NUMBER NOT NULL, /* 주문 진행상태 */
	M_ID VARCHAR2(50) NOT NULL, /* 주문자 */
	BIZ_DERIVERY NUMBER, /* 배송비 */
	P_O_MEMO VARCHAR2(300), /* 배송 메모 */
	P_O_DATE DATE NOT NULL, /* 주문 일자 */
	P_O_BOOKDATE DATE NOT NULL, /* 예약 날짜 */
	P_O_CNT NUMBER NOT NULL, /* 주문 수량 */
	P_O_PRICE NUMBER NOT NULL, /* 총 상품 가격 */
	P_O_TEXT VARCHAR2(60), /* 문구  */
	P_O_REC_NAME VARCHAR2(50) NOT NULL, /* 받는 사람 이름 */
	P_O_REC_CP VARCHAR2(50) NOT NULL, /* 받는 사람 번호 */
	P_O_REC_POST VARCHAR2(10) NOT NULL, /* 받는 사람 우편번호 */
	P_O_REC_BASIC_ADDR VARCHAR2(1000) NOT NULL, /* 받는 사람 기본주소 */
	P_O_REC_DETAIL_ADDR VARCHAR2(1000) NOT NULL /* 받는 사람 상세주소 */
);

COMMENT ON TABLE LIKEYCAKEY.PRODUCT_ORDER IS '완제품 케이크 주문';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_ORDER.P_O_NUM IS '주문 번호';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_ORDER.P_B_NUM IS '참조 게시글 번호';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_ORDER.S_NUM IS '주문 진행상태';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_ORDER.M_ID IS '주문자';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_ORDER.BIZ_DERIVERY IS '배송비';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_ORDER.P_O_MEMO IS '배송 메모';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_ORDER.P_O_DATE IS '주문 일자';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_ORDER.P_O_BOOKDATE IS '예약 날짜';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_ORDER.P_O_CNT IS '주문 수량';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_ORDER.P_O_PRICE IS '총 상품 가격';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_ORDER.P_O_TEXT IS '문구 ';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_ORDER.P_O_REC_NAME IS '받는 사람 이름';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_ORDER.P_O_REC_CP IS '받는 사람 번호';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_ORDER.P_O_REC_POST IS '받는 사람 우편번호';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_ORDER.P_O_REC_BASIC_ADDR IS '받는 사람 기본주소';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_ORDER.P_O_REC_DETAIL_ADDR IS '받는 사람 상세주소';

CREATE UNIQUE INDEX LIKEYCAKEY.PK_PRODUCT_ORDER
	ON LIKEYCAKEY.PRODUCT_ORDER (
		P_O_NUM ASC
	);

ALTER TABLE LIKEYCAKEY.PRODUCT_ORDER
	ADD
		CONSTRAINT PK_PRODUCT_ORDER
		PRIMARY KEY (
			P_O_NUM
		);

/* 상품 관련 QNA */
CREATE TABLE LIKEYCAKEY.PRODUCT_QNA (
	P_Q_NUM NUMBER NOT NULL, /* 상품 QNA 게시글 번호 */
	P_B_NUM NUMBER NOT NULL, /* 상품 원글 참조 번호 */
	M_ID VARCHAR2(100) NOT NULL, /* 상품 QNA 글쓴이 */
	P_Q_CONTENT VARCHAR2(4000) NOT NULL, /* 상품 QNA 글 내용 */
	P_Q_DATE DATE NOT NULL /* 상품 QNA 글 작성일 */
);

COMMENT ON TABLE LIKEYCAKEY.PRODUCT_QNA IS '상품 관련 QNA';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_QNA.P_Q_NUM IS '상품 QNA 게시글 번호';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_QNA.P_B_NUM IS '상품 원글 참조 번호';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_QNA.M_ID IS '상품 QNA 글쓴이';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_QNA.P_Q_CONTENT IS '상품 QNA 글 내용';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_QNA.P_Q_DATE IS '상품 QNA 글 작성일';

CREATE UNIQUE INDEX LIKEYCAKEY.PK_PRODUCT_QNA
	ON LIKEYCAKEY.PRODUCT_QNA (
		P_Q_NUM ASC
	);

ALTER TABLE LIKEYCAKEY.PRODUCT_QNA
	ADD
		CONSTRAINT PK_PRODUCT_QNA
		PRIMARY KEY (
			P_Q_NUM
		);

/* 상품 리뷰 */
CREATE TABLE LIKEYCAKEY.PRODUCT_REVIEW (
	P_R_NUM NUMBER NOT NULL, /* 리뷰 글 번호 */
	P_B_NUM NUMBER NOT NULL, /* 원글 참조 번호 */
	M_ID VARCHAR2(50) NOT NULL, /* 리뷰 글쓴이 */
	P_R_CONTENT VARCHAR2(4000) NOT NULL, /* 리뷰 글 내용 */
	P_R_DATE DATE NOT NULL, /* 리뷰 글 작성일 */
	P_R_LIKE NUMBER NOT NULL, /* 리뷰 좋아요 수 */
	P_R_BLACK NUMBER NOT NULL, /* 리뷰 신고 수 */
	P_R_FILE VARCHAR2(1000), /* 리뷰 이미지 */
	P_R_STAR NUMBER NOT NULL /* 리뷰 별점 */
);

COMMENT ON TABLE LIKEYCAKEY.PRODUCT_REVIEW IS '상품 리뷰';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_REVIEW.P_R_NUM IS '리뷰 글 번호';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_REVIEW.P_B_NUM IS '원글 참조 번호';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_REVIEW.M_ID IS '리뷰 글쓴이';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_REVIEW.P_R_CONTENT IS '리뷰 글 내용';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_REVIEW.P_R_DATE IS '리뷰 글 작성일';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_REVIEW.P_R_LIKE IS '리뷰 좋아요 수';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_REVIEW.P_R_BLACK IS '리뷰 신고 수';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_REVIEW.P_R_FILE IS '리뷰 이미지';

COMMENT ON COLUMN LIKEYCAKEY.PRODUCT_REVIEW.P_R_STAR IS '리뷰 별점';

CREATE UNIQUE INDEX LIKEYCAKEY.PK_PRODUCT_REVIEW
	ON LIKEYCAKEY.PRODUCT_REVIEW (
		P_R_NUM ASC
	);

ALTER TABLE LIKEYCAKEY.PRODUCT_REVIEW
	ADD
		CONSTRAINT PK_PRODUCT_REVIEW
		PRIMARY KEY (
			P_R_NUM
		);

/* 상풍 관련 QNA 댓글 */
CREATE TABLE LIKEYCAKEY.P_QNA_COM (
	P_Q_C_NUM NUMBER NOT NULL, /* 상품 QNA 댓글 번호 */
	P_Q_NUM NUMBER NOT NULL, /* 상품 QNA 원글 참조 번호 */
	M_ID VARCHAR2(50) NOT NULL, /* 상품 QNA 댓글쓴이 */
	P_Q_C_CONTENT VARCHAR2(4000) NOT NULL, /* 상품 QNA 댓글 내용 */
	P_Q_C_DATE DATE NOT NULL /* 상품 QNA 댓글 작성날짜 */
);

COMMENT ON TABLE LIKEYCAKEY.P_QNA_COM IS '상풍 관련 QNA 댓글';

COMMENT ON COLUMN LIKEYCAKEY.P_QNA_COM.P_Q_C_NUM IS '상품 QNA 댓글 번호';

COMMENT ON COLUMN LIKEYCAKEY.P_QNA_COM.P_Q_NUM IS '상품 QNA 원글 참조 번호';

COMMENT ON COLUMN LIKEYCAKEY.P_QNA_COM.M_ID IS '상품 QNA 댓글쓴이';

COMMENT ON COLUMN LIKEYCAKEY.P_QNA_COM.P_Q_C_CONTENT IS '상품 QNA 댓글 내용';

COMMENT ON COLUMN LIKEYCAKEY.P_QNA_COM.P_Q_C_DATE IS '상품 QNA 댓글 작성날짜';

CREATE UNIQUE INDEX LIKEYCAKEY.PK_P_QNA_COM
	ON LIKEYCAKEY.P_QNA_COM (
		P_Q_C_NUM ASC
	);

ALTER TABLE LIKEYCAKEY.P_QNA_COM
	ADD
		CONSTRAINT PK_P_QNA_COM
		PRIMARY KEY (
			P_Q_C_NUM
		);

/* 상품 리뷰 댓글 */
CREATE TABLE LIKEYCAKEY.P_REVIEW_COM (
	P_R_C_NUM NUMBER NOT NULL, /* 리뷰 댓글 번호 */
	P_R_NUM NUMBER NOT NULL, /* 리뷰 원글 참조 번호 */
	P_R_C_CONTENT VARCHAR2(4000) NOT NULL, /* 리뷰 댓글 내용 */
	P_R_C_DATE DATE NOT NULL /* 리뷰 댓글 작성일 */
);

COMMENT ON TABLE LIKEYCAKEY.P_REVIEW_COM IS '상품 리뷰 댓글';

COMMENT ON COLUMN LIKEYCAKEY.P_REVIEW_COM.P_R_C_NUM IS '리뷰 댓글 번호';

COMMENT ON COLUMN LIKEYCAKEY.P_REVIEW_COM.P_R_NUM IS '리뷰 원글 참조 번호';

COMMENT ON COLUMN LIKEYCAKEY.P_REVIEW_COM.P_R_C_CONTENT IS '리뷰 댓글 내용';

COMMENT ON COLUMN LIKEYCAKEY.P_REVIEW_COM.P_R_C_DATE IS '리뷰 댓글 작성일';

CREATE UNIQUE INDEX LIKEYCAKEY.PK_P_REVIEW_COM
	ON LIKEYCAKEY.P_REVIEW_COM (
		P_R_C_NUM ASC
	);

ALTER TABLE LIKEYCAKEY.P_REVIEW_COM
	ADD
		CONSTRAINT PK_P_REVIEW_COM
		PRIMARY KEY (
			P_R_C_NUM
		);

/* 주문 진행 단계 */
CREATE TABLE LIKEYCAKEY.STATUS (
	S_NUM NUMBER NOT NULL, /* 주문 진행단계 번호 */
	S_STATUS VARCHAR2(20) NOT NULL /* 주문 진행단계 설명 */
);

COMMENT ON TABLE LIKEYCAKEY.STATUS IS '주문 진행 단계';

COMMENT ON COLUMN LIKEYCAKEY.STATUS.S_NUM IS '주문 진행단계 번호';

COMMENT ON COLUMN LIKEYCAKEY.STATUS.S_STATUS IS '주문 진행단계 설명';

CREATE UNIQUE INDEX LIKEYCAKEY.PK_STATUS
	ON LIKEYCAKEY.STATUS (
		S_NUM ASC
	);

ALTER TABLE LIKEYCAKEY.STATUS
	ADD
		CONSTRAINT PK_STATUS
		PRIMARY KEY (
			S_NUM
		);

ALTER TABLE LIKEYCAKEY.BLACK_LIST
	ADD
		CONSTRAINT BLACK_LIST_FK_TUSER
		FOREIGN KEY (
			TUSER
		)
		REFERENCES LIKEYCAKEY.MEMBER (
			M_ID
		);

ALTER TABLE LIKEYCAKEY.BLACK_LIST
	ADD
		CONSTRAINT BLACK_LIST_FK_RUSER
		FOREIGN KEY (
			RUSER
		)
		REFERENCES LIKEYCAKEY.MEMBER (
			M_ID
		);

ALTER TABLE LIKEYCAKEY.CUSTOM_BOARD
	ADD
		CONSTRAINT FK_MEMBER_TO_CUSTOM_BOARD
		FOREIGN KEY (
			M_ID
		)
		REFERENCES LIKEYCAKEY.MEMBER (
			M_ID
		);

ALTER TABLE LIKEYCAKEY.CUSTOM_CREAM
	ADD
		CONSTRAINT FK_MEMBER_TO_COUSTOM_CREAM
		FOREIGN KEY (
			M_ID
		)
		REFERENCES LIKEYCAKEY.MEMBER (
			M_ID
		);

ALTER TABLE LIKEYCAKEY.CUSTOM_ORDER
	ADD
		CONSTRAINT FK_STATUS_TO_CUSTOM_ORDER
		FOREIGN KEY (
			S_NUM
		)
		REFERENCES LIKEYCAKEY.STATUS (
			S_NUM
		);

ALTER TABLE LIKEYCAKEY.CUSTOM_ORDER
	ADD
		CONSTRAINT FK_CBOARD_TO_CORDER
		FOREIGN KEY (
			C_B_NUM
		)
		REFERENCES LIKEYCAKEY.CUSTOM_BOARD (
			C_B_NUM
		);

ALTER TABLE LIKEYCAKEY.CUSTOM_ORDER
	ADD
		CONSTRAINT FK_MEMBER_TO_CUSTOM_ORDER
		FOREIGN KEY (
			M_ID
		)
		REFERENCES LIKEYCAKEY.MEMBER (
			M_ID
		);

ALTER TABLE LIKEYCAKEY.CUSTOM_SHEET
	ADD
		CONSTRAINT FK_MEMBER_TO_CUSTOM_SHEET
		FOREIGN KEY (
			M_ID
		)
		REFERENCES LIKEYCAKEY.MEMBER (
			M_ID
		);

ALTER TABLE LIKEYCAKEY.CUSTOM_SIZE
	ADD
		CONSTRAINT FK_MEMBER_TO_CUSTOM_SIZE
		FOREIGN KEY (
			M_ID
		)
		REFERENCES LIKEYCAKEY.MEMBER (
			M_ID
		);

ALTER TABLE LIKEYCAKEY.CUSTOM_TOPPING
	ADD
		CONSTRAINT FK_MEMBER_TO_CUSTOM_TOPPING
		FOREIGN KEY (
			M_ID
		)
		REFERENCES LIKEYCAKEY.MEMBER (
			M_ID
		);

ALTER TABLE LIKEYCAKEY.DELIVERY
	ADD
		CONSTRAINT FK_DELIVERY_BASIC_TO_DELIVERY
		FOREIGN KEY (
			D_NUM
		)
		REFERENCES LIKEYCAKEY.DELIVERY_BASIC (
			D_NUM
		);

ALTER TABLE LIKEYCAKEY.DELIVERY_BASIC
	ADD
		CONSTRAINT FK_PORDER_TO_DBASIC
		FOREIGN KEY (
			P_O_NUM
		)
		REFERENCES LIKEYCAKEY.PRODUCT_ORDER (
			P_O_NUM
		);

ALTER TABLE LIKEYCAKEY.HOME_QNA
	ADD
		CONSTRAINT FK_HOME_QNA_TO_HOME_QNA
		FOREIGN KEY (
			H_Q_RE_REF
		)
		REFERENCES LIKEYCAKEY.HOME_QNA (
			H_Q_NUM
		);

ALTER TABLE LIKEYCAKEY.HOME_QNA
	ADD
		CONSTRAINT FK_MEMBER_TO_HOME_QNA
		FOREIGN KEY (
			M_ID
		)
		REFERENCES LIKEYCAKEY.MEMBER (
			M_ID
		);

ALTER TABLE LIKEYCAKEY.H_QNA_COM
	ADD
		CONSTRAINT FK_H_QNA_COM_TO_H_QNA_COM
		FOREIGN KEY (
			H_Q_NUM
		)
		REFERENCES LIKEYCAKEY.H_QNA_COM (
			H_Q_C_NUM
		);

ALTER TABLE LIKEYCAKEY.H_QNA_COM
	ADD
		CONSTRAINT FK_MEMBER_TO_H_QNA_COM
		FOREIGN KEY (
			M_ID
		)
		REFERENCES LIKEYCAKEY.MEMBER (
			M_ID
		);

ALTER TABLE LIKEYCAKEY.MEMBER
	ADD
		CONSTRAINT FK_MEMBER_CODE_TO_MEMBER
		FOREIGN KEY (
			M_NUM
		)
		REFERENCES LIKEYCAKEY.MEMBER_CODE (
			M_NUM
		);

ALTER TABLE LIKEYCAKEY.MEMBER_BIZ
	ADD
		CONSTRAINT FK_MEMBER_TO_MEMBER_BIZ
		FOREIGN KEY (
			M_ID
		)
		REFERENCES LIKEYCAKEY.MEMBER (
			M_ID
		);

ALTER TABLE LIKEYCAKEY.MEMBER_BIZ
	ADD
		CONSTRAINT FK_MEMBER_CODE_TO_MEMBER_BIZ
		FOREIGN KEY (
			M_NUM
		)
		REFERENCES LIKEYCAKEY.MEMBER_CODE (
			M_NUM
		);

ALTER TABLE LIKEYCAKEY.MEMBER_LIKE
	ADD
		CONSTRAINT MEMBER_LIKE_FK_P_B_NUM
		FOREIGN KEY (
			P_B_NUM
		)
		REFERENCES LIKEYCAKEY.PRODUCT_BOARD (
			P_B_NUM
		);

ALTER TABLE LIKEYCAKEY.MEMBER_LIKE
	ADD
		CONSTRAINT MEMBER_LIKE_FK_M_ID
		FOREIGN KEY (
			M_ID
		)
		REFERENCES LIKEYCAKEY.MEMBER (
			M_ID
		);

ALTER TABLE LIKEYCAKEY.MEMBER_LIKE
	ADD
		CONSTRAINT MEMBER_LIKE_FK_C_B_NUM
		FOREIGN KEY (
			C_B_NUM
		)
		REFERENCES LIKEYCAKEY.CUSTOM_BOARD (
			C_B_NUM
		);

ALTER TABLE LIKEYCAKEY.PRODUCT_BOARD
	ADD
		CONSTRAINT FK_MEMBER_TO_PRODUCT_BOARD
		FOREIGN KEY (
			M_ID
		)
		REFERENCES LIKEYCAKEY.MEMBER (
			M_ID
		);

ALTER TABLE LIKEYCAKEY.PRODUCT_ORDER
	ADD
		CONSTRAINT FK_STATUS_TO_PRODUCT_ORDER
		FOREIGN KEY (
			S_NUM
		)
		REFERENCES LIKEYCAKEY.STATUS (
			S_NUM
		);

ALTER TABLE LIKEYCAKEY.PRODUCT_ORDER
	ADD
		CONSTRAINT FK_PBOARD_TO_PORDER
		FOREIGN KEY (
			P_B_NUM
		)
		REFERENCES LIKEYCAKEY.PRODUCT_BOARD (
			P_B_NUM
		);

ALTER TABLE LIKEYCAKEY.PRODUCT_ORDER
	ADD
		CONSTRAINT FK_MEMBER_TO_PRODUCT_ORDER
		FOREIGN KEY (
			M_ID
		)
		REFERENCES LIKEYCAKEY.MEMBER (
			M_ID
		);

ALTER TABLE LIKEYCAKEY.PRODUCT_QNA
	ADD
		CONSTRAINT FK_PBOARD_TO_PQNA
		FOREIGN KEY (
			P_B_NUM
		)
		REFERENCES LIKEYCAKEY.PRODUCT_BOARD (
			P_B_NUM
		);

ALTER TABLE LIKEYCAKEY.PRODUCT_REVIEW
	ADD
		CONSTRAINT FK_MEMBER_TO_PRODUCT_REVIEW
		FOREIGN KEY (
			M_ID
		)
		REFERENCES LIKEYCAKEY.MEMBER (
			M_ID
		);

ALTER TABLE LIKEYCAKEY.PRODUCT_REVIEW
	ADD
		CONSTRAINT FK_PBOARD_TO_PREVIEW
		FOREIGN KEY (
			P_B_NUM
		)
		REFERENCES LIKEYCAKEY.PRODUCT_BOARD (
			P_B_NUM
		);

ALTER TABLE LIKEYCAKEY.P_QNA_COM
	ADD
		CONSTRAINT FK_MEMBER_TO_P_QNA_COM
		FOREIGN KEY (
			M_ID
		)
		REFERENCES LIKEYCAKEY.MEMBER (
			M_ID
		);

ALTER TABLE LIKEYCAKEY.P_QNA_COM
	ADD
		CONSTRAINT FK_PRODUCT_QNA_TO_P_QNA_COM
		FOREIGN KEY (
			P_Q_NUM
		)
		REFERENCES LIKEYCAKEY.PRODUCT_QNA (
			P_Q_NUM
		);

ALTER TABLE LIKEYCAKEY.P_REVIEW_COM
	ADD
		CONSTRAINT FK_PREVIEW_TO_PRCOM
		FOREIGN KEY (
			P_R_NUM
		)
		REFERENCES LIKEYCAKEY.PRODUCT_REVIEW (
			P_R_NUM
		);
		
		
ALTER TABLE PRODUCT_ORDER RENAME COLUMN BIZ_DERIVERY to BIZ_DELIVERY;

alter table MEMBER_BIZ modify(BIZ_CUSTOM_YN varchar2(10));
alter table MEMBER_BIZ modify(BIZ_DELIVERY_YN varchar2(10));


-- 타입 컬럼 추가
alter table product_order add(p_o_type NUMBER);
alter table custom_order add(c_o_type NUMBER);



INSERT INTO STATUS (S_NUM, S_STATUS) VALUES(0,'구매취소');


-- 상품 QNA 컬럼 추가 상세페이지 원글 참조 번호 P_B_NUM
ALTER TABLE P_QNA_COM ADD(P_B_NUM NUMBER);

ALTER TABLE P_QNA_COM
ADD CONSTRAINTS FK_P_QNA_PBNUM FOREIGN KEY (P_B_NUM)
REFERENCES PRODUCT_BOARD(P_B_NUM);