-- USER DROP
DROP USER likeycakey CASCADE;

-- CREATE USER
CREATE USER likeycakey IDENTIFIED BY likeycakey;
GRANT RESOURCE, CONNECT TO likeycakey;


-- 1. MEMBER_CODE CREATE
/* 회원 분류 */
CREATE TABLE MEMBER_CODE (
	M_NUM NUMBER NOT NULL, /* 회원 분류 번호 */
	M_TYPE VARCHAR2(12) NOT NULL /* 회원 구분 타입 */
);

INSERT INTO MEMBER_CODE
VALUES (1, 'ADMIN');

INSERT INTO MEMBER_CODE
VALUES (2, 'NOR');

INSERT INTO MEMBER_CODE
VALUES (3, 'BIZ');

COMMENT ON TABLE MEMBER_CODE IS '회원 분류';
COMMENT ON COLUMN MEMBER_CODE.M_NUM IS '회원 분류 번호';
COMMENT ON COLUMN MEMBER_CODE.M_TYPE IS '회원 구분 타입';

ALTER TABLE MEMBER_CODE ADD
CONSTRAINT PK_MEMBER_CODE PRIMARY KEY ( M_NUM );

-- 2. MEMBER CREATE
CREATE TABLE MEMBER (
	M_ID VARCHAR2(50) NOT NULL, /* 회원 아이디 */
	M_NUM NUMBER NOT NULL, /* 회원 분류 번호 */
	M_PW VARCHAR2(50) NOT NULL, /* 회원 비밀번호 */
	M_NAME VARCHAR2(50) NOT NULL, /* 회원 이름 */
	M_EMAIL VARCHAR2(100), /* 회원 이메일 */
	M_POST VARCHAR2(10), /* 회원 우편번호 */
	M_BASIC_ADDR VARCHAR2(1000), /* 회원 기본주소 */
	M_DETAIL_ADDR VARCHAR2(1000), /* 회원 상세주소 */
	M_CP VARCHAR2(50), /* 회원 전화번호 */
	M_PHOTO VARCHAR2(2000), /* 회원 사진 */
	M_BLACKCNT NUMBER DEFAULT 0, /* 신고당한 횟수 */
	M_STATUS NUMBER DEFAULT 0/* 회원의 현재 블록 상태 */
);

ALTER TABLE MEMBER RENAME COLUMN M_` TO M_BLACKCNT;
COMMENT ON TABLE MEMBER IS '회원 및 관리자';
COMMENT ON COLUMN MEMBER.M_ID IS '회원 아이디';
COMMENT ON COLUMN MEMBER.M_NUM IS '회원 분류 번호';
COMMENT ON COLUMN MEMBER.M_PW IS '회원 비밀번호';
COMMENT ON COLUMN MEMBER.M_NAME IS '회원 이름';
COMMENT ON COLUMN MEMBER.M_EMAIL IS '회원 이메일';
COMMENT ON COLUMN MEMBER.M_POST IS '회원 우편번호';
COMMENT ON COLUMN MEMBER.M_BASIC_ADDR IS '회원 기본주소';
COMMENT ON COLUMN MEMBER.M_DETAIL_ADDR IS '회원 상세주소';
COMMENT ON COLUMN MEMBER.M_CP IS '회원 전화번호';
COMMENT ON COLUMN MEMBER.M_PHOTO IS '회원 사진';
COMMENT ON COLUMN MEMBER.M_BALCKCNT IS '신고당한 횟수';
COMMENT ON COLUMN MEMBER.M_STATUS IS '회원의 현재 블록 상태';


ALTER TABLE MEMBER ADD 
CONSTRAINT PK_MEMBER PRIMARY KEY (M_ID);

ALTER TABLE MEMBER ADD CONSTRAINT FK_MEMBER_CODE_TO_MEMBER
FOREIGN KEY (M_NUM) REFERENCES MEMBER_CODE (M_NUM);


-- 3. MEMBER_BIZ CREATE 
/* 사업지 회원 */
CREATE TABLE MEMBER_BIZ (
	M_ID VARCHAR2(50) NOT NULL, /* 회원 아이디 */
	M_NUM NUMBER NOT NULL, /* 회원 분류 번호 */
	BIZ_NAME VARCHAR2(50) NOT NULL, /* 사업장 이름 */
	BIZ_PN VARCHAR2(20) NOT NULL, /* 사업장 전화번호 */
	BIZ_NUM VARCHAR2(50) NOT NULL, /* 사업자 등록번호 */
	BIZ_DELIVERY NUMBER, /* 배송비 */
	MASTER_NAME VARCHAR2(50) NOT NULL, /* 담당자 이름 */
	BIZ_DELIVERY_YN VARCHAR2(2) NOT NULL, /* 배송가능 여부 */
	BIZ_CUSTOM_YN VARCHAR2(2) NOT NULL /* 케이크 커스텀 가능여부 */
);

COMMENT ON TABLE MEMBER_BIZ IS '사업지 회원';
COMMENT ON COLUMN MEMBER_BIZ.M_ID IS '회원 아이디';
COMMENT ON COLUMN MEMBER_BIZ.M_NUM IS '회원 분류 번호';
COMMENT ON COLUMN MEMBER_BIZ.BIZ_NAME IS '사업장 이름';
COMMENT ON COLUMN MEMBER_BIZ.BIZ_PN IS '사업장 전화번호';
COMMENT ON COLUMN MEMBER_BIZ.BIZ_NUM IS '사업자 등록번호';
COMMENT ON COLUMN MEMBER_BIZ.BIZ_DELIVERY IS '배송비';
COMMENT ON COLUMN MEMBER_BIZ.MASTER_NAME IS '담당자 이름';
COMMENT ON COLUMN MEMBER_BIZ.BIZ_DELIVERY_YN IS '배송가능 여부';
COMMENT ON COLUMN MEMBER_BIZ.BIZ_CUSTOM_YN IS '케이크 커스텀 가능여부';

ALTER TABLE MEMBER_BIZ ADD 
CONSTRAINT FK_MEMBER_CODE_TO_MEMBER_BIZ
FOREIGN KEY (M_NUM)
REFERENCES MEMBER_CODE (M_NUM);

ALTER TABLE MEMBER_BIZ ADD
CONSTRAINT FK_MEMBER_TO_MEMBER_BIZ
FOREIGN KEY (M_ID)
REFERENCES MEMBER (M_ID);


-- PRODUCT_BOARD
/* 완제품 케이크 상세페이지 */
CREATE TABLE PRODUCT_BOARD (
	P_B_NUM NUMBER NOT NULL, /* 게시글 번호 */
	M_ID VARCHAR2(50) NOT NULL, /* 회원 아이디 */
	P_NAME VARCHAR2(100) NOT NULL, /* 케이크 이름 */
	P_PRICE VARCHAR2(100) NOT NULL, /* 케이크 가격 */
	P_IMG VARCHAR2(100) NOT NULL, /* 케이크 이미지 */
	P_SIZE NUMBER NOT NULL, /* 케이크 규격 */
	P_CM VARCHAR2(20) NOT NULL, /* 케이크 크기(CM) */
	P_COUNT NUMBER NOT NULL, /* 케이크 재고 */
	P_COUNT_LIMIT NUMBER DEFAULT 0 NOT NULL, /* 일일판매제한 개수 */
	P_B_MINI_TITLE VARCHAR2(100) NOT NULL, /* 게시글 소 제목 */
	P_B_MINI_CONTENT VARCHAR2(2000) NOT NULL, /* 게시글 소내용 */
	P_B_CONTENT VARCHAR2(4000) NOT NULL, /* 게시글 내용 */
	P_B_LIKE NUMBER DEFAULT 0 NOT NULL, /* 게시글 좋아요 수 */
	P_B_READCNT NUMBER DEFAULT 0 NOT NULL, /* 게시글 조회 수 */
	P_B_YN VARCHAR2(2) NOT NULL
	CONSTRAINT P_BOARD_YN_CK CHECK(P_B_YN IN('Y','N')), /* 당일 구매여부 */
	P_B_WARN VARCHAR2(2000) NOT NULL, /* 예약시 주의사항 */
	P_B_TAG VARCHAR2(2000) NOT NULL /* 게시글 태그 */
);

CREATE SEQUENCE SEQ_P_B_NUM 
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE
;

COMMENT ON TABLE PRODUCT_BOARD IS '완제품 케이크 상세페이지';
COMMENT ON COLUMN PRODUCT_BOARD.P_B_NUM IS '게시글 번호';
COMMENT ON COLUMN PRODUCT_BOARD.M_ID IS '회원 아이디';
COMMENT ON COLUMN PRODUCT_BOARD.P_NAME IS '케이크 이름';
COMMENT ON COLUMN PRODUCT_BOARD.P_PRICE IS '케이크 가격';
COMMENT ON COLUMN PRODUCT_BOARD.P_IMG IS '케이크 이미지';
COMMENT ON COLUMN PRODUCT_BOARD.P_SIZE IS '케이크 규격';
COMMENT ON COLUMN PRODUCT_BOARD.P_CM IS '케이크 크기(CM)';
COMMENT ON COLUMN PRODUCT_BOARD.P_COUNT IS '케이크 재고';
COMMENT ON COLUMN PRODUCT_BOARD.P_COUNT_LIMIT IS '일일판매제한 개수';
COMMENT ON COLUMN PRODUCT_BOARD.P_B_MINI_TITLE IS '게시글 소 제목';
COMMENT ON COLUMN PRODUCT_BOARD.P_B_MINI_CONTENT IS '게시글 소내용';
COMMENT ON COLUMN PRODUCT_BOARD.P_B_CONTENT IS '게시글 내용';
COMMENT ON COLUMN PRODUCT_BOARD.P_B_LIKE IS '게시글 좋아요 수';
COMMENT ON COLUMN PRODUCT_BOARD.P_B_READCNT IS '게시글 조회 수';
COMMENT ON COLUMN PRODUCT_BOARD.P_B_YN IS '당일 구매여부';
COMMENT ON COLUMN PRODUCT_BOARD.P_B_WARN IS '예약시 주의사항';
COMMENT ON COLUMN PRODUCT_BOARD.P_B_TAG IS '게시글 태그';

ALTER TABLE PRODUCT_BOARD ADD
CONSTRAINT PK_PRODUCT_BOARD
PRIMARY KEY (P_B_NUM);

ALTER TABLE PRODUCT_BOARD ADD
CONSTRAINT FK_MEMBER_TO_PRODUCT_BOARD
FOREIGN KEY (M_ID)
REFERENCES MEMBER (M_ID);


-- CUSTOM_BOARD CREATE
/* 커스터마이징 케이크 상세페이지 */
CREATE TABLE CUSTOM_BOARD (
	C_B_NUM NUMBER NOT NULL, /* 게시글 번호 */
	M_ID VARCHAR2(50) NOT NULL, /* 회원 아이디 */
	C_B_MINI_TITLE VARCHAR2(100) NOT NULL, /* 게시글 소제목 */
	C_B_MINI_CONTENT VARCHAR2(2000) NOT NULL, /* 게시글 소내용 */
	C_B_CONTENT VARCHAR2(4000) NOT NULL, /* 게시글 내용 */
	C_B_LIKE NUMBER DEFAULT 0 NOT NULL , /* 게시글 좋아요 수 */
	C_B_READCNT NUMBER DEFAULT 0 NOT NULL , /* 게시글 조회 수 */
	C_B_TAG VARCHAR2(2000) NOT NULL, /* 게시글 태그 */
	C_B_WARN VARCHAR2(2000) NOT NULL, /* 예약시 주의사항 */
	C_B_NAME VARCHAR2(100) NOT NULL, /* 게시글 이름 */
	C_B_PRICE NUMBER NOT NULL /* 기본 가격 */
);

CREATE SEQUENCE SEQ_C_B_NUM
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE
;

COMMENT ON TABLE CUSTOM_BOARD IS '커스터마이징 케이크 상세페이지';
COMMENT ON COLUMN CUSTOM_BOARD.C_B_NUM IS '게시글 번호';
COMMENT ON COLUMN CUSTOM_BOARD.M_ID IS '회원 아이디';
COMMENT ON COLUMN CUSTOM_BOARD.C_B_MINI_TITLE IS '게시글 소제목';
COMMENT ON COLUMN CUSTOM_BOARD.C_B_MINI_CONTENT IS '게시글 소내용';
COMMENT ON COLUMN CUSTOM_BOARD.C_B_CONTENT IS '게시글 내용';
COMMENT ON COLUMN CUSTOM_BOARD.C_B_LIKE IS '게시글 좋아요 수';
COMMENT ON COLUMN CUSTOM_BOARD.C_B_READCNT IS '게시글 조회 수';
COMMENT ON COLUMN CUSTOM_BOARD.C_B_TAG IS '게시글 태그';
COMMENT ON COLUMN CUSTOM_BOARD.C_B_WARN IS '예약시 주의사항';
COMMENT ON COLUMN CUSTOM_BOARD.C_B_NAME IS '게시글 이름';
COMMENT ON COLUMN CUSTOM_BOARD.C_B_PRICE IS '기본 가격';


ALTER TABLE CUSTOM_BOARD ADD CONSTRAINT PK_CUSTOM_BOARD
PRIMARY KEY (C_B_NUM);

ALTER TABLE CUSTOM_BOARD ADD
CONSTRAINT FK_MEMBER_TO_CUSTOM_BOARD
FOREIGN KEY (M_ID)REFERENCES MEMBER (M_ID);
		

-- HOME_QNA CREATE
/* 홈페이지 관련 QNA */
CREATE TABLE HOME_QNA (
	H_Q_NUM NUMBER NOT NULL, /* QNA 게시글 번호 */
	M_ID VARCHAR2(50) NOT NULL, /* QNA 게시글 글쓴이 */
	H_Q_CONTENT VARCHAR2(4000) NOT NULL, /* QNA 게시글 내용 */
	H_Q_TITLE VARCHAR2(500) NOT NULL, /* QNA 게시글 제목 */
	H_Q_DATE DATE DEFAULT SYSDATE NOT NULL , /* QNA 게시글 작성일 */
	H_Q_RE_REF NUMBER DEFAULT 0 NOT NULL , /* 원글 참조 번호 */
	H_Q_RE_LEV NUMBER DEFAULT 0 NOT NULL , /* 답글 레벨 */
	H_Q_RE_SEQ NUMBER DEFAULT 0 NOT NULL  /* 답글 시퀀스 */
);

CREATE SEQUENCE SEQ_H_Q_NUM 
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE
;

COMMENT ON TABLE HOME_QNA IS '홈페이지 관련 QNA';
COMMENT ON COLUMN HOME_QNA.H_Q_NUM IS 'QNA 게시글 번호';
COMMENT ON COLUMN HOME_QNA.M_ID IS 'QNA 게시글 글쓴이';
COMMENT ON COLUMN HOME_QNA.H_Q_CONTENT IS 'QNA 게시글 내용';
COMMENT ON COLUMN HOME_QNA.H_Q_TITLE IS 'QNA 게시글 제목';
COMMENT ON COLUMN HOME_QNA.H_Q_DATE IS 'QNA 게시글 작성일';
COMMENT ON COLUMN HOME_QNA.H_Q_RE_REF IS '원글 참조 번호';
COMMENT ON COLUMN HOME_QNA.H_Q_RE_LEV IS '답글 레벨';
COMMENT ON COLUMN HOME_QNA.H_Q_RE_SEQ IS '답글 시퀀스';

ALTER TABLE HOME_QNA ADD CONSTRAINT PK_HOME_QNA
PRIMARY KEY (H_Q_NUM);

ALTER TABLE HOME_QNA ADD CONSTRAINT FK_MEMBER_TO_HOME_QNA
FOREIGN KEY (M_ID)
REFERENCES MEMBER (M_ID);

ALTER TABLE HOME_QNA ADD CONSTRAINT FK_HOME_QNA_TO_HOME_QNA
FOREIGN KEY (H_Q_RE_REF)
REFERENCES HOME_QNA (H_Q_NUM);


-- H_QNA_COM
/* 홈페이지 관련 QNA 댓글 */
CREATE TABLE H_QNA_COM (
	H_Q_C_NUM NUMBER NOT NULL, /* 홈페이지 QNA 댓글 번호 */
	H_Q_NUM NUMBER NOT NULL, /* 홈페이지 QNA 게시글 참조번호 */
	M_ID VARCHAR2(50) NOT NULL, /* 홈페이지 QNA 댓글 글쓴이 */
	H_Q_C_CONTENT VARCHAR2(4000) NOT NULL, /* 홈페이지 QNA 댓글 내용 */
	H_Q_C_DATE DATE DEFAULT SYSDATE NOT NULL , /* 홈페이지 QNA 댓글 작성날짜 */
	H_Q_C_RE_LEV NUMBER DEFAULT 0 NOT NULL , /* 홈페이지 QNA 댓글 레벨 */
	H_Q_C_RE_SEQ NUMBER DEFAULT 0 NOT NULL  /* 홈페이지 QNA 댓글 시퀀스 */
);

CREATE SEQUENCE SEQ_H_Q_C_NUM
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;


COMMENT ON TABLE H_QNA_COM IS '홈페이지 관련 QNA 댓글';
COMMENT ON COLUMN H_QNA_COM.H_Q_C_NUM IS '홈페이지 QNA 댓글 번호';
COMMENT ON COLUMN H_QNA_COM.H_Q_NUM IS '홈페이지 QNA 게시글 참조번호';
COMMENT ON COLUMN H_QNA_COM.M_ID IS '홈페이지 QNA 댓글 글쓴이';
COMMENT ON COLUMN H_QNA_COM.H_Q_C_CONTENT IS '홈페이지 QNA 댓글 내용';
COMMENT ON COLUMN H_QNA_COM.H_Q_C_DATE IS '홈페이지 QNA 댓글 작성날짜';
COMMENT ON COLUMN H_QNA_COM.H_Q_C_RE_LEV IS '홈페이지 QNA 댓글 레벨';
COMMENT ON COLUMN H_QNA_COM.H_Q_C_RE_SEQ IS '홈페이지 QNA 댓글 시퀀스';


ALTER TABLE H_QNA_COM ADD CONSTRAINT PK_H_QNA_COM
PRIMARY KEY (H_Q_C_NUM);

ALTER TABLE H_QNA_COM ADD CONSTRAINT FK_MEMBER_TO_H_QNA_COM
FOREIGN KEY (M_ID)REFERENCES MEMBER (M_ID);

ALTER TABLE H_QNA_COM ADD CONSTRAINT FK_H_QNA_COM_TO_H_QNA_COM
FOREIGN KEY (H_Q_NUM)
REFERENCES H_QNA_COM (H_Q_C_NUM);



-- PRODUCT_QNA
/* 상품 관련 QNA */
CREATE TABLE PRODUCT_QNA (
	P_Q_NUM NUMBER NOT NULL, /* 상품 QNA 게시글 번호 */
	P_B_NUM NUMBER NOT NULL, /* 상품 원글 참조 번호 */
	M_ID VARCHAR2(100) NOT NULL, /* 상품 QNA 글쓴이 */
	P_Q_CONTENT VARCHAR2(4000) NOT NULL, /* 상품 QNA 글 내용 */
	P_Q_DATE DATE DEFAULT SYSDATE NOT NULL  /* 상품 QNA 글 작성일 */
);

CREATE SEQUENCE SEQ_P_Q_NUM
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

COMMENT ON TABLE PRODUCT_QNA IS '상품 관련 QNA';
COMMENT ON COLUMN PRODUCT_QNA.P_Q_NUM IS '상품 QNA 게시글 번호';
COMMENT ON COLUMN PRODUCT_QNA.P_B_NUM IS '상품 원글 참조 번호';
COMMENT ON COLUMN PRODUCT_QNA.M_ID IS '상품 QNA 글쓴이';
COMMENT ON COLUMN PRODUCT_QNA.P_Q_CONTENT IS '상품 QNA 글 내용';
COMMENT ON COLUMN PRODUCT_QNA.P_Q_DATE IS '상품 QNA 글 작성일';

ALTER TABLE PRODUCT_QNA ADD CONSTRAINT PK_PRODUCT_QNA
PRIMARY KEY (P_Q_NUM);

ALTER TABLE PRODUCT_QNA ADD CONSTRAINT FK_PBOARD_TO_PQNA
FOREIGN KEY (P_B_NUM) REFERENCES PRODUCT_BOARD (P_B_NUM);



-- P_QNA_COM
/* 상풍 관련 QNA 댓글 */
CREATE TABLE P_QNA_COM (
	P_Q_C_NUM NUMBER NOT NULL, /* 상품 QNA 댓글 번호 */
	P_Q_NUM NUMBER NOT NULL, /* 상품 QNA 원글 참조 번호 */
	M_ID VARCHAR2(50) NOT NULL, /* 상품 QNA 댓글쓴이 */
	P_Q_C_CONTENT VARCHAR2(4000) NOT NULL, /* 상품 QNA 댓글 내용 */
	P_Q_C_DATE DATE DEFAULT SYSDATE NOT NULL  /* 상품 QNA 댓글 작성날짜 */
);

CREATE SEQUENCE SEQ_P_Q_C_NUM
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

COMMENT ON TABLE P_QNA_COM IS '상풍 관련 QNA 댓글';

COMMENT ON COLUMN P_QNA_COM.P_Q_C_NUM IS '상품 QNA 댓글 번호';

COMMENT ON COLUMN P_QNA_COM.P_Q_NUM IS '상품 QNA 원글 참조 번호';

COMMENT ON COLUMN P_QNA_COM.M_ID IS '상품 QNA 댓글쓴이';

COMMENT ON COLUMN P_QNA_COM.P_Q_C_CONTENT IS '상품 QNA 댓글 내용';

COMMENT ON COLUMN P_QNA_COM.P_Q_C_DATE IS '상품 QNA 댓글 작성날짜';

CREATE UNIQUE INDEX PK_P_QNA_COM
	ON P_QNA_COM (
		P_Q_C_NUM ASC
	);

ALTER TABLE P_QNA_COM
	ADD
		CONSTRAINT PK_P_QNA_COM
		PRIMARY KEY (
			P_Q_C_NUM
		);

ALTER TABLE P_QNA_COM ADD CONSTRAINT FK_PRODUCT_QNA_TO_P_QNA_COM
FOREIGN KEY (P_Q_NUM)REFERENCES PRODUCT_QNA (P_Q_NUM);

ALTER TABLE P_QNA_COM ADD
CONSTRAINT FK_MEMBER_TO_P_QNA_COM
FOREIGN KEY (M_ID)REFERENCES MEMBER (M_ID);
	


-- PRODUCT_REVIEW
/* 상품 리뷰 */
CREATE TABLE PRODUCT_REVIEW (
	P_R_NUM NUMBER NOT NULL, /* 리뷰 글 번호 */
	P_B_NUM NUMBER NOT NULL, /* 원글 참조 번호 */
	M_ID VARCHAR2(50) NOT NULL, /* 리뷰 글쓴이 */
	P_R_CONTENT VARCHAR2(4000) NOT NULL, /* 리뷰 글 내용 */
	P_R_DATE DATE DEFAULT SYSDATE NOT NULL , /* 리뷰 글 작성일 */
	P_R_LIKE NUMBER DEFAULT 0 NOT NULL , /* 리뷰 좋아요 수 */
	P_R_BLACK NUMBER DEFAULT 0 NOT NULL , /* 리뷰 신고 수 */
	P_R_FILE VARCHAR2(1000), /* 리뷰 이미지 */
	P_R_STAR NUMBER DEFAULT 0 NOT NULL  /* 리뷰 별점 */
);

CREATE SEQUENCE SEQ_P_R_NUM
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

COMMENT ON TABLE PRODUCT_REVIEW IS '상품 리뷰';

COMMENT ON COLUMN PRODUCT_REVIEW.P_R_NUM IS '리뷰 글 번호';

COMMENT ON COLUMN PRODUCT_REVIEW.P_B_NUM IS '원글 참조 번호';

COMMENT ON COLUMN PRODUCT_REVIEW.M_ID IS '리뷰 글쓴이';

COMMENT ON COLUMN PRODUCT_REVIEW.P_R_CONTENT IS '리뷰 글 내용';

COMMENT ON COLUMN PRODUCT_REVIEW.P_R_DATE IS '리뷰 글 작성일';

COMMENT ON COLUMN PRODUCT_REVIEW.P_R_LIKE IS '리뷰 좋아요 수';

COMMENT ON COLUMN PRODUCT_REVIEW.P_R_BLACK IS '리뷰 신고 수';

COMMENT ON COLUMN PRODUCT_REVIEW.P_R_FILE IS '리뷰 이미지';

COMMENT ON COLUMN PRODUCT_REVIEW.P_R_STAR IS '리뷰 별점';


ALTER TABLE PRODUCT_REVIEW ADD CONSTRAINT PK_PRODUCT_REVIEW
PRIMARY KEY (P_R_NUM);

ALTER TABLE PRODUCT_REVIEW ADD
CONSTRAINT FK_PBOARD_TO_PREVIEW
FOREIGN KEY (P_B_NUM)REFERENCES PRODUCT_BOARD (P_B_NUM);

ALTER TABLE PRODUCT_REVIEW ADD
CONSTRAINT FK_MEMBER_TO_PRODUCT_REVIEW
FOREIGN KEY (M_ID)REFERENCES MEMBER (M_ID);



-- P_REVIEW_COM
/* 상품 리뷰 댓글 */
CREATE TABLE P_REVIEW_COM (
	P_R_C_NUM NUMBER NOT NULL, /* 리뷰 댓글 번호 */
	P_R_NUM NUMBER NOT NULL, /* 리뷰 원글 참조 번호 */
	P_R_C_CONTENT VARCHAR2(4000) NOT NULL, /* 리뷰 댓글 내용 */
	P_R_C_DATE DATE  DEFAULT SYSDATE NOT NULL  /* 리뷰 댓글 작성일 */
);

CREATE SEQUENCE SEQ_P_R_C_NUM
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

COMMENT ON TABLE P_REVIEW_COM IS '상품 리뷰 댓글';
COMMENT ON COLUMN P_REVIEW_COM.P_R_C_NUM IS '리뷰 댓글 번호';
COMMENT ON COLUMN P_REVIEW_COM.P_R_NUM IS '리뷰 원글 참조 번호';
COMMENT ON COLUMN P_REVIEW_COM.P_R_C_CONTENT IS '리뷰 댓글 내용';
COMMENT ON COLUMN P_REVIEW_COM.P_R_C_DATE IS '리뷰 댓글 작성일';

ALTER TABLE P_REVIEW_COM ADD CONSTRAINT PK_P_REVIEW_COM
PRIMARY KEY (P_R_C_NUM);

ALTER TABLE P_REVIEW_COM ADD CONSTRAINT FK_PREVIEW_TO_PRCOM
FOREIGN KEY (P_R_NUM)REFERENCES PRODUCT_REVIEW (P_R_NUM);




-- STATUS
/* 주문 진행 단계 */
CREATE TABLE STATUS (
	S_NUM NUMBER NOT NULL, /* 주문 진행단계 번호 */
	S_STATUS VARCHAR2(20) NOT NULL /* 주문 진행단계 설명 */
);

COMMENT ON TABLE STATUS IS '주문 진행 단계';
COMMENT ON COLUMN STATUS.S_NUM IS '주문 진행단계 번호';
COMMENT ON COLUMN STATUS.S_STATUS IS '주문 진행단계 설명';

ALTER TABLE STATUS ADD CONSTRAINT PK_STATUS
PRIMARY KEY (S_NUM);


-- PRODUCT_ORDER
/* 완제품 케이크 주문 */
CREATE TABLE PRODUCT_ORDER (
	P_O_NUM NUMBER NOT NULL, /* 주문 번호 */
	P_B_NUM NUMBER NOT NULL, /* 참조 게시글 번호 */
	S_NUM NUMBER NOT NULL, /* 주문 진행상태 */
	M_ID VARCHAR2(50) NOT NULL, /* 주문자 */
	BIZ_DERIVERY NUMBER, /* 배송비 */
	P_O_MEMO VARCHAR2(300), /* 배송 메모 */
	P_O_DATE DATE DEFAULT SYSDATE NOT NULL , /* 주문 일자 */
	P_O_BOOKDATE DATE DEFAULT SYSDATE NOT NULL , /* 예약 날짜 */
	P_O_CNT NUMBER NOT NULL, /* 주문 수량 */
	P_O_PRICE NUMBER NOT NULL, /* 총 상품 가격 */
	P_O_TEXT VARCHAR2(60), /* 문구  */
	P_O_REC_NAME VARCHAR2(50) NOT NULL, /* 받는 사람 이름 */
	P_O_REC_CP VARCHAR2(50) NOT NULL, /* 받는 사람 번호 */
	P_O_REC_POST VARCHAR2(10) NOT NULL, /* 받는 사람 우편번호 */
	P_O_REC_BASIC_ADDR VARCHAR2(1000) NOT NULL, /* 받는 사람 기본주소 */
	P_O_REC_DETAIL_ADDR VARCHAR2(1000) NOT NULL /* 받는 사람 상세주소 */
);

COMMENT ON TABLE PRODUCT_ORDER IS '완제품 케이크 주문';
COMMENT ON COLUMN PRODUCT_ORDER.P_O_NUM IS '주문 번호';
COMMENT ON COLUMN PRODUCT_ORDER.P_B_NUM IS '참조 게시글 번호';
COMMENT ON COLUMN PRODUCT_ORDER.S_NUM IS '주문 진행상태';
COMMENT ON COLUMN PRODUCT_ORDER.M_ID IS '주문자';
COMMENT ON COLUMN PRODUCT_ORDER.BIZ_DERIVERY IS '배송비';
COMMENT ON COLUMN PRODUCT_ORDER.P_O_MEMO IS '배송 메모';
COMMENT ON COLUMN PRODUCT_ORDER.P_O_DATE IS '주문 일자';
COMMENT ON COLUMN PRODUCT_ORDER.P_O_BOOKDATE IS '예약 날짜';
COMMENT ON COLUMN PRODUCT_ORDER.P_O_CNT IS '주문 수량';
COMMENT ON COLUMN PRODUCT_ORDER.P_O_PRICE IS '총 상품 가격';
COMMENT ON COLUMN PRODUCT_ORDER.P_O_TEXT IS '문구 ';
COMMENT ON COLUMN PRODUCT_ORDER.P_O_REC_NAME IS '받는 사람 이름';
COMMENT ON COLUMN PRODUCT_ORDER.P_O_REC_CP IS '받는 사람 번호';
COMMENT ON COLUMN PRODUCT_ORDER.P_O_REC_POST IS '받는 사람 우편번호';
COMMENT ON COLUMN PRODUCT_ORDER.P_O_REC_BASIC_ADDR IS '받는 사람 기본주소';
COMMENT ON COLUMN PRODUCT_ORDER.P_O_REC_DETAIL_ADDR IS '받는 사람 상세주소';

ALTER TABLE PRODUCT_ORDER ADD CONSTRAINT PK_PRODUCT_ORDER
PRIMARY KEY (P_O_NUM);

ALTER TABLE PRODUCT_ORDER ADD CONSTRAINT FK_MEMBER_TO_PRODUCT_ORDER
FOREIGN KEY (M_ID)
REFERENCES MEMBER (M_ID);

ALTER TABLE PRODUCT_ORDER ADD CONSTRAINT FK_PBOARD_TO_PORDER
FOREIGN KEY (P_B_NUM) REFERENCES PRODUCT_BOARD (P_B_NUM);

ALTER TABLE PRODUCT_ORDER ADD CONSTRAINT FK_STATUS_TO_PRODUCT_ORDER
FOREIGN KEY (S_NUM)
REFERENCES STATUS (S_NUM);



-- CUSTOM_ORDER
/* 커스텀 케이크 주문 */
CREATE TABLE CUSTOM_ORDER (
	C_O_NUM NUMBER NOT NULL, /* 커스텀 케이크 주문 번호 */
	C_B_NUM NUMBER NOT NULL, /* 커스텀 케이크 페이지 참조 번호 */
	S_NUM NUMBER NOT NULL, /* 주문 진행상태 */
	M_ID VARCHAR2(50) NOT NULL, /* 주문자 */
	BIZ_DELIVERY NUMBER, /* 배송비 */
	C_O_MEMO VARCHAR2(300), /* 배송 메모 */
	C_O_DATE DATE DEFAULT SYSDATE NOT NULL , /* 커스텀 케이크 주문 일자 */
	C_O_BOOKDATE DATE DEFAULT SYSDATE NOT NULL , /* 커스텀 케이크 예약 날짜 */
	C_O_CNT NUMBER NOT NULL, /* 커스텀 케이크 주문수량 */
	C_O_PRICE NUMBER NOT NULL, /* 총 삼품 가격 */
	C_O_TEXT VARCHAR2(60), /* 케이크 문구 */
	C_O_SIZE VARCHAR2(20) NOT NULL, /* 커스텀 케이크 사이즈 */
	C_O_SHEET VARCHAR2(20) NOT NULL, /* 커스텀 케이크 선택 시트 */
	C_O_TOPPING VARCHAR2(20) NOT NULL, /* 커스텀 케이크 선택 토핑 */
	C_O_CREAM VARCHAR2(20) NOT NULL, /* 커스텀 케이크 선택 크림 */
	C_O_REC_NAME VARCHAR2(50) NOT NULL, /* 받는 사람 이름 */
	C_O_REC_CP VARCHAR2(50) NOT NULL, /* 받는 사람 전화번호 */
	C_O_REC_POST VARCHAR2(10) NOT NULL, /* 받는 사람 우편번호 */
	C_O_REC_BASIC_ADDR VARCHAR2(1000) NOT NULL, /* 받는 사람 기본주소 */
	C_O_REC_DETAIL_ADDR VARCHAR2(1000) NOT NULL /* 받는 사람 상세주소 */
);

COMMENT ON TABLE CUSTOM_ORDER IS '커스텀 케이크 주문';
COMMENT ON COLUMN CUSTOM_ORDER.C_O_NUM IS '커스텀 케이크 주문 번호';
COMMENT ON COLUMN CUSTOM_ORDER.C_B_NUM IS '커스텀 케이크 페이지 참조 번호';
COMMENT ON COLUMN CUSTOM_ORDER.S_NUM IS '주문 진행상태';
COMMENT ON COLUMN CUSTOM_ORDER.M_ID IS '주문자';
COMMENT ON COLUMN CUSTOM_ORDER.BIZ_DELIVERY IS '배송비';
COMMENT ON COLUMN CUSTOM_ORDER.C_O_MEMO IS '배송 메모';
COMMENT ON COLUMN CUSTOM_ORDER.C_O_DATE IS '커스텀 케이크 주문 일자';
COMMENT ON COLUMN CUSTOM_ORDER.C_O_BOOKDATE IS '커스텀 케이크 예약 날짜';
COMMENT ON COLUMN CUSTOM_ORDER.C_O_CNT IS '커스텀 케이크 주문수량';
COMMENT ON COLUMN CUSTOM_ORDER.C_O_PRICE IS '총 삼품 가격';
COMMENT ON COLUMN CUSTOM_ORDER.C_O_TEXT IS '케이크 문구';
COMMENT ON COLUMN CUSTOM_ORDER.C_O_SIZE IS '커스텀 케이크 사이즈';
COMMENT ON COLUMN CUSTOM_ORDER.C_O_SHEET IS '커스텀 케이크 선택 시트';
COMMENT ON COLUMN CUSTOM_ORDER.C_O_TOPPING IS '커스텀 케이크 선택 토핑';
COMMENT ON COLUMN CUSTOM_ORDER.C_O_CREAM IS '커스텀 케이크 선택 크림';
COMMENT ON COLUMN CUSTOM_ORDER.C_O_REC_NAME IS '받는 사람 이름';
COMMENT ON COLUMN CUSTOM_ORDER.C_O_REC_CP IS '받는 사람 전화번호';
COMMENT ON COLUMN CUSTOM_ORDER.C_O_REC_POST IS '받는 사람 우편번호';
COMMENT ON COLUMN CUSTOM_ORDER.C_O_REC_BASIC_ADDR IS '받는 사람 기본주소';
COMMENT ON COLUMN CUSTOM_ORDER.C_O_REC_DETAIL_ADDR IS '받는 사람 상세주소';

ALTER TABLE CUSTOM_ORDER ADD CONSTRAINT PK_CUSTOM_ORDER
PRIMARY KEY (C_O_NUM);

ALTER TABLE CUSTOM_ORDER ADD CONSTRAINT FK_MEMBER_TO_CUSTOM_ORDER
FOREIGN KEY (M_ID)
REFERENCES MEMBER (M_ID);

ALTER TABLE CUSTOM_ORDER ADD CONSTRAINT FK_CBOARD_TO_CORDER
FOREIGN KEY (C_B_NUM)
REFERENCES CUSTOM_BOARD (C_B_NUM);

ALTER TABLE CUSTOM_ORDER ADD CONSTRAINT FK_STATUS_TO_CUSTOM_ORDER
FOREIGN KEY (S_NUM) REFERENCES STATUS (S_NUM);
		

-- DELIVERY_BASIC
/* 배송 기본 정보 */
CREATE TABLE DELIVERY_BASIC (
	D_NUM VARCHAR2(20) NOT NULL, /* 운송장 번호 */
	P_O_NUM NUMBER NOT NULL, /* 주문번호 */
	D_COMPANY VARCHAR2(300) NOT NULL /* 택배사 */
);

COMMENT ON TABLE DELIVERY_BASIC IS '배송 기본 정보';

COMMENT ON COLUMN DELIVERY_BASIC.D_NUM IS '운송장 번호';

COMMENT ON COLUMN DELIVERY_BASIC.P_O_NUM IS '주문번호';

COMMENT ON COLUMN DELIVERY_BASIC.D_COMPANY IS '택배사';


ALTER TABLE DELIVERY_BASIC ADD CONSTRAINT PK_DELIVERY_BASIC
PRIMARY KEY (D_NUM);

ALTER TABLE DELIVERY_BASIC ADD CONSTRAINT FK_PORDER_TO_DBASIC
FOREIGN KEY (P_O_NUM)
REFERENCES PRODUCT_ORDER (P_O_NUM);


-- DELIVERY
/* 배송관련 테이블 */
CREATE TABLE DELIVERY (
	D_NUM VARCHAR2(20) NOT NULL, /* 운송장 번호 */
	D_DATE DATE DEFAULT SYSDATE NOT NULL , /* 처리 일시 */
	D_LOCATION VARCHAR2(100) NOT NULL, /* 택배 현재 위치 */
	DV_STATUS VARCHAR2(50) NOT NULL, /* 배송 상태 */
	DM_CP VARCHAR2(20) /* 배송기사 전화번호 */
);

COMMENT ON TABLE DELIVERY IS '배송관련 테이블';
COMMENT ON COLUMN DELIVERY.D_NUM IS '운송장 번호';
COMMENT ON COLUMN DELIVERY.D_DATE IS '처리 일시';
COMMENT ON COLUMN DELIVERY.D_LOCATION IS '택배 현재 위치';
COMMENT ON COLUMN DELIVERY.DV_STATUS IS '배송 상태';
COMMENT ON COLUMN DELIVERY.DM_CP IS '배송기사 전화번호';

ALTER TABLE DELIVERY ADD CONSTRAINT FK_DELIVERY_BASIC_TO_DELIVERY
FOREIGN KEY (D_NUM)REFERENCES DELIVERY_BASIC (D_NUM);


-- CUSTOM_SHEET
/* 커스텀 시트 */
CREATE TABLE CUSTOM_SHEET (
	SH_NUM VARCHAR2(20) NOT NULL, /* 시트 번호 */
	M_ID VARCHAR2(50) NOT NULL, /* 사업자 회원 아이디 */
	SH_NAME VARCHAR2(50) NOT NULL, /* 시트 종류 */
	SH_PRICE NUMBER NOT NULL /* 시트 추가 가격 */
);

COMMENT ON TABLE CUSTOM_SHEET IS '커스텀 시트';
COMMENT ON COLUMN CUSTOM_SHEET.SH_NUM IS '시트 번호';
COMMENT ON COLUMN CUSTOM_SHEET.M_ID IS '사업자 회원 아이디';
COMMENT ON COLUMN CUSTOM_SHEET.SH_NAME IS '시트 종류';
COMMENT ON COLUMN CUSTOM_SHEET.SH_PRICE IS '시트 추가 가격';

ALTER TABLE CUSTOM_SHEET ADD CONSTRAINT PK_CUSTOM_SHEET
PRIMARY KEY (SH_NUM);

ALTER TABLE CUSTOM_SHEET ADD CONSTRAINT FK_MEMBER_TO_CUSTOM_SHEET
FOREIGN KEY (M_ID)
REFERENCES MEMBER (M_ID);
		
		
-- CUSTOM_CREAM
/* 커스텀 크림 */
CREATE TABLE COUSTOM_CREAM (
	CR_NUM VARCHAR2(20) NOT NULL, /* 크림 번호 */
	M_ID VARCHAR2(50) NOT NULL, /* 사업자 회원 아이디 */
	CR_NAME VARCHAR2(50) NOT NULL, /* 크림 종류 */
	CR_PRICE NUMBER NOT NULL /* 크림 추가 가격 */
);

COMMENT ON TABLE COUSTOM_CREAM IS '커스텀 크림';
COMMENT ON COLUMN COUSTOM_CREAM.CR_NUM IS '크림 번호';
COMMENT ON COLUMN COUSTOM_CREAM.M_ID IS '사업자 회원 아이디';
COMMENT ON COLUMN COUSTOM_CREAM.CR_NAME IS '크림 종류';
COMMENT ON COLUMN COUSTOM_CREAM.CR_PRICE IS '크림 추가 가격';

ALTER TABLE COUSTOM_CREAM ADD CONSTRAINT PK_COUSTOM_CREAM
PRIMARY KEY (CR_NUM);

ALTER TABLE COUSTOM_CREAM ADD CONSTRAINT FK_MEMBER_TO_COUSTOM_CREAM
FOREIGN KEY (M_ID)
REFERENCES MEMBER (M_ID);
		
		
-- CUSTOM_TOPPING
/* 커스텀 토핑 */
CREATE TABLE CUSTOM_TOPPING (
	TP_NUM VARCHAR2(20) NOT NULL, /* 토핑 번호 */
	M_ID VARCHAR2(50) NOT NULL, /* 사업자 회원 아이디 */
	TP_NAME VARCHAR2(50) NOT NULL, /* 토핑 종류 */
	TP_PRICE NUMBER NOT NULL /* 토핑 추가 가격 */
);

COMMENT ON TABLE CUSTOM_TOPPING IS '커스텀 토핑';
COMMENT ON COLUMN CUSTOM_TOPPING.TP_NUM IS '토핑 번호';
COMMENT ON COLUMN CUSTOM_TOPPING.M_ID IS '사업자 회원 아이디';
COMMENT ON COLUMN CUSTOM_TOPPING.TP_NAME IS '토핑 종류';
COMMENT ON COLUMN CUSTOM_TOPPING.TP_PRICE IS '토핑 추가 가격';

ALTER TABLE CUSTOM_TOPPING ADD CONSTRAINT PK_CUSTOM_TOPPING
PRIMARY KEY (TP_NUM);

ALTER TABLE CUSTOM_TOPPING ADD CONSTRAINT FK_MEMBER_TO_CUSTOM_TOPPING
FOREIGN KEY (M_ID)
REFERENCES MEMBER (M_ID);
		
		
-- CUSTOM_SIZE
/* 커스텀 사이즈 */
CREATE TABLE CUSTOM_SIZE (
	SIZE_NUM VARCHAR2(20) NOT NULL, /* 사이즈 번호 */
	M_ID VARCHAR2(50) NOT NULL, /* 사업자 회원 아이디 */
	SIZE_NAME VARCHAR2(50) NOT NULL, /* 사이즈 종류 */
	SIZE_PRICE NUMBER NOT NULL /* 사이즈 추가 가격 */
);

COMMENT ON TABLE CUSTOM_SIZE IS '커스텀 사이즈';
COMMENT ON COLUMN CUSTOM_SIZE.SIZE_NUM IS '사이즈 번호';
COMMENT ON COLUMN CUSTOM_SIZE.M_ID IS '사업자 회원 아이디';
COMMENT ON COLUMN CUSTOM_SIZE.SIZE_NAME IS '사이즈 종류';
COMMENT ON COLUMN CUSTOM_SIZE.SIZE_PRICE IS '사이즈 추가 가격';

ALTER TABLE CUSTOM_SIZE ADD CONSTRAINT PK_CUSTOM_SIZE
PRIMARY KEY (SIZE_NUM);

ALTER TABLE CUSTOM_SIZE ADD CONSTRAINT FK_MEMBER_TO_CUSTOM_SIZE
FOREIGN KEY (M_ID)
REFERENCES MEMBER (M_ID);


